### ISSUE TITLE
specify interactions between characters and combining characters

### ISSUE THREAD

**Issue by timo** [jeml-lang/jeml#3]
an example being starting a string with a combining character; how do you do it in jeml? for example, when a `"̈` is found at the start of a string, does that result in a string starting with a loose combiner, or is it a syntax error? if i understand correctly, there's even combining characters that go before the base character, but i just can't find good info on that; something with Prepend_Concatenation_Mark maybe? Anyway, in theory that means there'd want to be a decision whether a lone prepended combining character before a " will end a quoted string or not

**Comment by judah-caruso** [comment]
I'm not sure I fully understand what you mean. Could you give me a written example?

And I think it mostly depends on how JEML should handle strings going forward. If I'm understanding your question correctly, using the `"""` syntax for strings would mean that your value gets parsed **literally**, so a "lone prepended combining character before a [quote]" would **not** end a quoted string.
